### ISSUE TITLE
Accepting or declining match outside of steam

### ISSUE THREAD

**Issue by arslanmkhan** [paralin/Dota2#17]
Hi,
I am trying to accept or decline match request outside of steam. Initially i was using steam kit to achieve it but i was told that i can't do it without hooking the steam client. I did it and was able to get match found event out side of game then i tried to accept/decline the match but i didn't receive anything. 
I am using following code

`var requestMatch = new ClientGCMsgProtobuf<CMsgReadyUp>`
`((uint)EDOTAGCMsg.k_EMsgGCReadyUp);`
`requestMatch.Body.state = DOTALobbyReadyState.DOTALobbyReadyState_DECLINED;`

`gameCoordinator.Send(requestMatch, APPID);`

I am trying to achieve same thing with dota2 library. I am looking into LobbyDump project. i havent found a clue yet. Dota.GameClient looks promissing but its broken for source2 engine. I would like to know 
1)  Can I track match found event and then accept/ decline it outside of the game using dota2 library?
2) Should i wait for the update of dota.gameclient?
3) if i can't do it with dota2 and dota.gameclient won't be fixed in near future as it requires lot of work then can i do it with steamkit? Is the code i wrote above is correct am i missing something here like ready_up_key information?

Thanks

**Comment by sbx320** [comment]
Theoretically accepting a match using this library or SteamKit works. However accepting a game requires a correct ready_up_key, which I'm not sure how to get yet.

**Comment by paralin** [comment]
I could reverse engineer how to get the ready_up_key, but I'd rather not. It's there for a reason. They don't want bots queuing.

Right now I'm not willing to put in the effort to crack something in direct opposition to the intended reason for it being there. And I don't recommend you do either.

**Comment by luxalpa** [comment]
> I could reverse engineer how to get the ready_up_key, but I'd rather not. It's there for a reason. They don't want bots queuing.

Could you still do it? I want a bot host my own custom game, but all custom game lobbies also require ready-up :(

Or maybe you could just roughly tell me how you'd do it. My IDA Pro, Nethook and Wireshark are ready :P
