### ISSUE TITLE
Need help sending messages to a chat channel

### ISSUE THREAD

**Issue by Gufalagupagup** [paralin/Dota2#19]
How can I connect and send message to a regional chat channel , for example, Bucharest, Romania ?
How can I get the channel ID ... I couldn't find a way to do it .

Also, how do I send a chat message to the current lobby ?

**Comment by uside** [comment]
Lobby channel ID is "Lobby_" + lobby.id

**Comment by paralin** [comment]
Steps:
1. Join chat. For lobby, it's Lobby_ + lobby.id as @uSide says, with the chat type set to lobby
2. Save the channel ID from the join response.
3. Send messages using that ID.

**Comment by paralin** [comment]
If you're still stuck try using NetHook from Steamkit2 to watch the messages going back and forth. That's how this library is engineered, for the most part.
