### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Simon1093** [paralin/Dota2#21]
Hello everyone,

This is not really an issue but rather a question about how to use this library.

I tried to get such data as PlayerProfile, ProfileCard, MatchResult or ChatChannelList:

dota.RequestPlayerProfile(76561198165152222);
dota.RequestProfileCards(204887666);
dota.RequestMatchResult(2739541715);
dota.RequestChatChannelList();

But it returns nothing. Can you show me an example of how to get, let say, user's Profile Card?

Thank you in advance !

**Comment by paralin** [comment]
You have to put handlers in for the responses. You already add handlers for steam kit events, so you need to add some for the dota 2 events. 

I could implement some kind of asynchronous await api but right now it's left to the user to handle these things.

**Comment by Simon1093** [comment]
Thank you, got it!
