### ISSUE TITLE
Use library to get match statistics from practice lobby

### ISSUE THREAD

**Issue by shcizo** [paralin/Dota2#26]
I want to let a bot start a lobby, wait for a set amount time then launch the lobby and after the match is played get the match stats. My idea was to listen to the "Dota2.GC.Dota.Internal.DOTA_GameState.DOTA_GAMERULES_STATE_POST_GAME"-state but I noticed that the bot cant enter the game. Since users that havent been part of the lobby cant request match-details, do you know if there is any other way doing this?

**Comment by ghost** [comment]
Interested, anyone have any info?

**Comment by paralin** [comment]
lobby won't wait for bots to start.

**Comment by shcizo** [comment]
Seems like it cant be done :(

**Comment by paralin** [comment]
Reread what I said.......

**Comment by shcizo** [comment]
I have reread it but unfortunatly your comment does not help me understand if its doable or not.

**Comment by paralin** [comment]
Sooo the fact that the lobby WILL start even if the bot doesn't load in isn't helpful?

I wish I had this much help when I started out :)

**Comment by shcizo** [comment]
If the bot sits in player pool or as broadcaster/spectator my lobbys does NOT start. It fails and throws me back to the lobby gui again.  The only way I have gotten my lobby to start is to have the bot leave the game as it starts.

**Comment by paralin** [comment]
Sorry man but I've done this in prod for years and you're wrong. Try again. Make sure you have a "real" player on radiant and dire minimum.

**Comment by paralin** [comment]
Actually. If that still doesn't work then maybe the restriction is only removed for ticketed games? Not sure. Haven't tried without a ticket for a while. Let me know if you manage to get it to work.

**Comment by ghost** [comment]
I managed to get the match outcome by sticking the bot in the player pool and waiting for lobby match outcome. 

`dota.JoinTeam(DOTA_GC_TEAM.DOTA_GC_TEAM_PLAYER_POOL);`

But even with this, you can't get detailed info, like paralin says, you can only do that with tickets.

**Comment by paralin** [comment]
You can still get detailed info. Remember that the bots can see everything a regular player could. As a regular player, can you not see stats / replays for your recent private matches?

**Comment by shcizo** [comment]
Ok, I have come to the same conclusion as Rapt0rs. If the bot cant connect to the game/server you are not able to see detailed stats for a private lobby game even if you were in the actual lobby. IIRC you cant even watch the .dem replay-file in the client if you wasnt part of the game, when it comes to private lobbies.

**Comment by paralin** [comment]
I think you're correct on this one.

**Comment by shcizo** [comment]
Ye, Im afraid so...
