### ISSUE TITLE
bot can't invite friend to trade in dota2 game client?

### ISSUE THREAD

**Issue by lesonclc** [paralin/Dota2#33]
now i know use this plugin can invite to lobby,to party,can sent channel msg etc.
but i want to know how to invite friend to trade in dota2 game client  .
i can't find any interface or method in this plugin. how to do it?
i want made a steambot which can start trade in steamclient, also hope it can 
start trade in dota2 gameclient, just like we can invite friend trade  in dota2 game.
i think bot can do this ,right?

**Comment by paralin** [comment]
https://github.com/Jessecar96/SteamBot
