### ISSUE TITLE
can see bot create lobby name in source 2

### ISSUE THREAD

**Issue by vodcms** [paralin/Dota2#6]
can see bot create lobby name in source 2

**Comment by vodcms** [comment]
create league id lobby  is can't find in list

**Comment by paralin** [comment]
It works fine. You're doing something wrong. You cannot specify league ID unless you have a ticket and the bot has the admin ticket for it. You can only search by "gameName" not by password.

**Comment by vodcms** [comment]
thank you!  i fix  it now.
