### ISSUE TITLE
in dota2 reborn bot cant leave lobby.

### ISSUE THREAD

**Issue by vodcms** [paralin/Dota2#7]
in dota2 reborn bot cant leave lobby. until restart bot. befer source 1 is ok

**Comment by sbx320** [comment]
What exactly do you do to use to make the bot leave the lobby? For reference this code seems to work fine for me in Reborn:

``` csharp
        public void LeaveLobby()
        {
            dota.AbandonGame();
            dota.LeaveLobby();
            LeaveChatChannel();
        }
```

**Comment by paralin** [comment]
@sbx320 that's the exact same code I use and it works fine. So confirming
this isn't a bug (again)
